version: "3.9"
services:
    server:
      image: "python:3.7-alpine"
      volumes: 
        - ./code:/code
      entrypoint: python /code/serverDriver.py 
      stdin_open: true
      tty: true
    client1:
      image: "python:3.7-alpine"
      volumes: 
        - ./code:/code
      entrypoint: python /code/clientDriver.py
      stdin_open: true
      tty: true
    client2:
      image: "python:3.7-alpine"
      volumes: 
        - ./code:/code
      entrypoint: python /code/clientDriver.py
      stdin_open: true
      tty: true
    client3:
      image: "python:3.7-alpine"
      volumes: 
        - ./code:/code
      entrypoint: python /code/clientDriver.py
      stdin_open: true
      tty: true
    client4:
      image: "python:3.7-alpine"
      volumes: 
        - ./code:/code
      entrypoint: python /code/clientDriver.py
      stdin_open: true
      tty: true