version: "3.9"
services:
    server:
      image: "python:3.7-alpine"
      volumes: 
        - ./code:/code
      entrypoint: python /code/driver.py manager 
      stdin_open: true
      tty: true
    client1:
      image: "python:3.7-alpine"
      volumes: 
        - ./code:/code
      entrypoint: python /code/driver.py player CLIENT1
      stdin_open: true
      tty: true
    client2:
      image: "python:3.7-alpine"
      volumes: 
        - ./code:/code
      entrypoint: python /code/driver.py player CLIENT2
      stdin_open: true
      tty: true
    client3:
      image: "python:3.7-alpine"
      volumes: 
        - ./code:/code
      entrypoint: python /code/driver.py player CLIENT3
      stdin_open: true
      tty: true
    client4:
      image: "python:3.7-alpine"
      volumes: 
        - ./code:/code
      entrypoint: python /code/driver.py player CLIENT4 start CLIENT1 3
      stdin_open: true
      tty: true